//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
